### ISSUE TITLE
Найти и описать API для получения исторических данных индексов

### ISSUE THREAD

**Issue by DmitryMogilnikov** [DmitryMogilnikov/stock-indices-forecasting#12]
- [ ] Найти нужные запросы, возможно опираясь на [документацию](https://iss.moex.com/iss/reference/)

**Comment by ExtremCode** [comment]
Я нашёл репозиторий, где уже описаны некоторые API запросы, в том числе получение исторических данных
https://github.com/WLM1ke/apimoex/blob/master/apimoex/requests.py
