### ISSUE TITLE
Реализовать подсчет количества дней снижения процентного роста на n %

### ISSUE THREAD

**Issue by DmitryMogilnikov** [DmitryMogilnikov/stock-indices-forecasting#15]
Таблица с примером: https://docs.google.com/spreadsheets/d/1RlsHCqfZ52VV4amRB4WuEZAVGsgPCZkq/edit?usp=sharing&ouid=102175296666856273786&rtpof=true&sd=true

API:
https://github.com/WLM1ke/apimoex/blob/master/apimoex/requests.py

На вход подаются значения процентного роста интегральной суммы. Для каждого значения расчитать, за сколько дней оно снизилось на n % (приблизительно, понятно что целых чисел там не будет, надо задать погрешность)

**Comment by almostinf** [comment]
[PR](https://github.com/DmitryMogilnikov/stock-indices-forecasting/pull/20)
