### ISSUE TITLE
Описать API backend-а.

### ISSUE THREAD

**Issue by YuriiPetrovich** [DmitryMogilnikov/stock-indices-forecasting#23]
Составить описание запросов к бэку. Куда послылать запросы (и какие get, post,...), и что придет в ответ.

**Comment by DmitryMogilnikov** [comment]
Добавил описание запросов в ручках api для взаимодействия с временными рядами:
![image](https://github.com/DmitryMogilnikov/stock-indices-forecasting/assets/107568738/a22170ce-f9e4-492a-ba3a-2fe9dc877ccd)

Остальной функционал будет описываться по мере добавления
