### ISSUE TITLE
Сверстать Frontend часть проекта согласно макету.

### ISSUE THREAD

**Issue by YuriiPetrovich** [DmitryMogilnikov/stock-indices-forecasting#25]
Ссылка на макет в фигме:

https://www.figma.com/file/sxU2vhaXfGJSo0i2PBc1Zz/Frontend-scheme?type=design&node-id=0%3A1&mode=design&t=NcU00FkucCEdOWSv-1

Логику на данном этапе прописывать не требуется. 
С дополнительными вопросами можно обращаться к @Kordebalet232 .

**Comment by sssaaammmuuurrraaaiii** [comment]
(Frontend) Сделана первостепенная часть макета, подробнее: 1cd9481a4ab3d87a6bb3924a0ced0730a8baabe7

**Comment by sssaaammmuuurrraaaiii** [comment]
(Frontend) Вёрстка Frontend-части проекта согласно макету завершена, финальный вариант: 3532fbbd82516b5206cf1c2496af5b0bb5aafbc2
