### ISSUE TITLE
Встретиться с заказчиком по проекту

### ISSUE THREAD

**Issue by DmitryMogilnikov** [DmitryMogilnikov/stock-indices-forecasting#3]
Провести встречу с заказчиком, выяснить требования и ожидания, предъявляемые к конечному продукту.

Отписать по результатам встречи в комментарии/бэклог.

**Comment by YuriiPetrovich** [comment]
Встреча проведена. Требования для первого этапа: 
1. Реализовать выгрузку архивов значений фондовых индексов за заданный срок
2. Реализовать подсчет интегральной суммы значений и расчет процента роста показателей
3. Реализовать подсчет количества дней снижения процентного роста на n %
4. Веб интерфейс - на усмотрение команды, без конкретных требований
Таблица с примером: https://docs.google.com/spreadsheets/d/1RlsHCqfZ52VV4amRB4WuEZAVGsgPCZkq/edit?usp=sharing&ouid=102175296666856273786&rtpof=true&sd=true

После выполнения первого этапа провести демонстрацию заказчику и обсудить следующий этап работы.

**Comment by YuriiPetrovich** [comment]
Встреча проведена. Требования для первого этапа: 
1. Реализовать выгрузку архивов значений фондовых индексов за заданный срок
2. Реализовать подсчет интегральной суммы значений и расчет процента роста показателей
3. Реализовать подсчет количества дней снижения процентного роста на n %
4. Веб интерфейс - на усмотрение команды, без конкретных требований
Таблица с примером: https://docs.google.com/spreadsheets/d/1RlsHCqfZ52VV4amRB4WuEZAVGsgPCZkq/edit?usp=sharing&ouid=102175296666856273786&rtpof=true&sd=true

После выполнения первого этапа провести демонстрацию заказчику и обсудить следующий этап работы.
