### ISSUE TITLE
Изучить взаимодействие с биржевыми сервисами

### ISSUE THREAD

**Issue by DmitryMogilnikov** [DmitryMogilnikov/stock-indices-forecasting#5]
- [x] Исследовать наличие API у различных бирж (в частности будем рассматривать [Московскую биржу](https://www.moex.com/ru/indices))

**Comment by almostinf** [comment]
https://iss.moex.com/iss/engines/stock/markets/index/securities.json?lang=ru&_=1696417851889 тут очень много полезной инфы

**Comment by DmitryMogilnikov** [comment]
Нашел список всех запросов, по которым можно обращаться к API мосбиржи
https://iss.moex.com/iss/reference/

Также прикрепляю ссылку на руководство разработчика:
https://www.moex.com/a2193

Доп. статья по взаимодействию с API (с примерами запросов):
https://habr.com/ru/articles/486716/
