### ISSUE TITLE
Построить файловую структуру проекта

### ISSUE THREAD

**Issue by DmitryMogilnikov** [DmitryMogilnikov/stock-indices-forecasting#9]
- [x] Выстроить архитектуру
- [x] Решить, какая БД будет использоваться

**Comment by DmitryMogilnikov** [comment]
Файловая структура backend части проекта включает в себя следующие модули:

- api: описание ручек которые выводятся в Swagger UI
- core: конфигурационные файлы (файлы с настройками)
- db: взаимодействие с базой данных (Redis)
- docs: файлы с документацией к проекту
- schemas: схемы для запросов (request, response)
- service: основные функции реализующие бизнес-логику
- tests: тесты (в идеале повторяют структуру директории src)
- main.py: точка входа в приложение

**Comment by DmitryMogilnikov** [comment]
Файловая структура backend части проекта включает в себя следующие модули:

api: описание ручек которые выводятся в Swagger UI
core: конфигурационные файлы (файлы с настройками)
db: взаимодействие с базой данных (Redis)
docs: файлы с документацией к проекту
schemas: схемы для запросов (request, response)
service: основные функции реализующие бизнес-логику
tests: тесты (в идеале повторяют структуру директории src)
main.py: точка входа в приложение

**Comment by sevryukov** [comment]
@DmitryMogilnikov здравствуйте.

Уточните, пожалуйста, почему в качестве СУБД выбран Redis?

**Comment by DmitryMogilnikov** [comment]
@sevryukov здравствуйте.

Фактически наша задача не подразумевает наличие какой-то базы данных.
Redis был выбран в качестве некоторого кэша данных, которые необходимы для проведения расчетов по следующим причинам:
- Сервис должен работать быстро в режиме on-line, но каждый раз забирать данные через http может быть достаточно долго. Поэтому было принято решение сохранять те данные, которые уже запрашивались пользователем.
- Высокая скорость записи и чтения в сравнении с классическими SQL.
- Redis предоставляет простой интерфейс, что идеально подходит для MVP решения.
- У Redis есть встроенная поддержка типа данных временных рядов, по сути на данном этапе это единственный формат данных, который мы собираемся хранить.
- В случае, если в сервисе появятся высоконагруженные расчеты, с которыми не всегда сможет справляться fastapi background_tasks, Redis может выступать в качестве брокера сообщений в связке с Celery. Из-за того, что у Redis из коробки есть возможность использовать различные бд, которые фактически отделены друг от друга не будет необходимости разворачивать дополнительную базу данных для этих целей.

**Comment by sevryukov** [comment]
> Сервис должен работать быстро в режиме on-line

Это требование заказчика? Оно изложено устно?

@DmitryMogilnikov

**Comment by DmitryMogilnikov** [comment]
@sevryukov

Насчет того, является ли это требованием заказчика, скорее нет. 
Но с точки зрения пользователя проекта, лично мне бы хотелось, чтобы ожидание ответа было минимальным.

К тому же, я думаю, что сохранять данные, которые уже однажды были получены, является хорошей практикой, так как догрузить небольшую часть данных всегда проще и быстрее, чем выгружать данные за большой промежуток времени

**Comment by sevryukov** [comment]
@DmitryMogilnikov as you wish, but
> Но с точки зрения пользователя проекта, лично мне бы хотелось, чтобы ожидание ответа было минимальным.
1. Пользователя продукта (программы), а не проекта...
2. Заказчик не всегда = пользователь.
3. Важно понимать ещё и то, каким образом будет осуществляться поставка. Архитектуры приложений, включающие различные СУБД, чаще всего сопряжены с большим кол-вом настроек и повышенными требованиями к хостингу. Т.е. может получиться так, что продукт архитектурно красивый, а развернуть и экономно его использовать не представляется возможным.
4. Предыдущее особенно важно тогда, когда на ранних итерациях есть желание (и у заказчика и у исполнителя) быстрее получить первую версию и согласовать ожидания и требования.

> К тому же, я думаю, что сохранять данные, которые уже однажды были получены, является хорошей практикой, так как догрузить небольшую часть данных всегда проще и быстрее, чем выгружать данные за большой промежуток времени

Это смотря о каких данных и какого объёма идёт речь. Файл с постобработанными данными в каком-то смысле тоже является вариантом кеширования. СУБД хороша тогда, когда начинаем масштабировать, управлять, обрабатывать (с помощью запросов) данные, когда как для прототипа подойдёт любой файл формата JSON|CSV|XML и даже XLS

В общем пока кажется, что выбор сделан с преждевременной оптимизацией. Будем посмотреть :)

**Comment by DmitryMogilnikov** [comment]
@sevryukov Спасибо большое, я не думал с этой точки зрения.
